version: 2

models:
  - name: int_orders_margin
    description: aggregated data for each order
    columns:
      - name: orders_id
        tests:
          - not_null
          - unique
      - name: date_date
        tests:
          - not_null
      - name: revenue
        description: sum of revenue for order_id
        tests:
          - not_null
      - name: quantity
        description: sum of quantity for order_id
        tests:
          - not_null
      - name: purchase_cost
        description: sum of purchase cost for order_id
        tests:
          - not_null
      - name: margin
        description: sum of margin for order_id
        tests:
          - not_null
  - name: int_orders_operational
    description: operational_margin for each order
    columns:
      - name: orders_id
        tests:
          - not_null
          - unique
      - name: date_date
        tests:
          - not_null
      - name: operational_margin
        tests:
          - not_null
  - name: int_sales_margin
    description: data on each product in each order
    columns:
      - name: products_id
        tests:
          - not_null
      - name: date_date
        tests:
          - not_null
      - name: orders_id
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: purchase_price
        tests:
          - not_null
      - name: purchase_cost
        description: multiplication quantity, purchase price
        tests:
          - not_null
      - name: margin
    tests:
     - unique:
        column_name: "(products_id || '_' || orders_id)"
  - name: int_campaigns
    description: cost data for paid campaigns
    columns:
       - name: date_date
         tests:
            - not_null
       - name: paid_source
         tests:
              - not_null
       - name: campaign_key
         tests:
            - not_null
       - name: campaign_name
         tests:
              - not_null
       - name: ads_cost
         tests:
              - not_null
       - name: impression
         tests:
              - not_null
       - name: click
         tests:
              - not_null
    tests:
     - unique:
        column_name: "(date_date || '_' || campaign_key)"
  - name: int_campaigns_day
    description: aggregated cost data for paid campaigns per day
    columns:
       - name: date_date
         tests:
            - not_null
            - unique
       - name: ads_cost
         tests:
              - not_null
       - name: ads_impression
         tests:
              - not_null
       - name: ads_clicks
         tests:
              - not_null