version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product catalog, 1 row per product_id with coorresponding purchase_price
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
          - name: purchse_price 
            description: renamed as purchase_price
            tests:
              - not_null
      - name: sales
        identifier: raw_gz_sales
        description: sales catalog, 1 row per product_id sold with coorresponding order_id etc
        columns:
          - name: date_date
            description: date of purchase
            tests:
              - not_null
          - name: orders_id
            tests:
              - not_null
          - name: pdt_id
            description: renamed as products_id
            tests:
              - not_null
          - name: revenue
            description: total revenue per products_id sold
            tests:
              - not_null
          - name: quantity
            description: quantity of product_id in order
            tests:
              - not_null
        tests:
           - unique:
               column_name: "(pdt_id || '_' || orders_id)"
      - name: ship
        identifier: raw_gz_ship
        description: shipping catalog, 1 row per order_id shipped with corresponding costs
        columns:
          - name: orders_id
            tests:
             - not_null
             - unique
          - name: shipping_fee
            description: renamed as ship_fee, what customer paid for shipping
            tests:
              - not_null
          - name: logcost 
            description: renamed as log_cost
            tests:
              - not_null
          - name: ship_cost
            description: shipping costs
            tests:
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: list of adwords campaigns for each day
        columns: 
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            description: always Adwords
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            description: renamed as campaign_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
        tests:
           - unique:
               column_name: "(date_date || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: list of bing campaigns for each day
        columns:
         - name: date_date
           tests:
            - not_null
         - name: paid_source
           description: always Bing
           tests:
              - not_null
         - name: campaign_key
           tests:
            - not_null
         - name: camPGN_name
           description: renamed as campaign_name
           tests:
              - not_null
         - name: ads_cost
           tests:
              - not_null
         - name: impression
           tests:
              - not_null
         - name: click
           tests:
              - not_null
        tests:
           - unique:
               column_name: "(date_date || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: list of criteo campaigns for each day
        columns:
         - name: date_date
           tests:
            - not_null
         - name: paid_source
           description: always Criteo
           tests:
              - not_null
         - name: campaign_key
           tests:
            - not_null
         - name: camPGN_name
           description: renamed as campaign_name
           tests:
              - not_null
         - name: ads_cost
           tests:
              - not_null
         - name: impression
           tests:
              - not_null
         - name: click
           tests:
              - not_null
        tests:
           - unique:
               column_name: "(date_date || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: list of facebook campaigns for each day
        columns:
         - name: date_date
           tests:
            - not_null
         - name: paid_source
           description: always Facebook
           tests:
              - not_null
         - name: campaign_key
           tests:
            - not_null
         - name: camPGN_name
           description: renamed as campaign_name
           tests:
              - not_null
         - name: ads_cost
           tests:
              - not_null
         - name: impression
           tests:
              - not_null
         - name: click
           tests:
              - not_null
        tests:
           - unique:
               column_name: "(date_date || '_' || campaign_key)"




