version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: product catalog, 1 row per product_id with coorresponding purchase_price
        columns:
          - name: products_id
          - name: purchase_price
      - name: sales
        identifier: raw_gz_sales
        description: sales catalog, 1 row per product_id sold with coorresponding order_id etc
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
          - name: products_id
          - name: revenue
            description: total revenue per product_id sold
          - name: quantity
            description: quantity of product_id in order
      - name: ship
        identifier: raw_gz_ship
        description: shipping catalog, 1 row per order_id shipped with corresponding costs
        columns:
          - name: orders_id
          - name: ship_fee
            description: what customer paid for shipping
          - name: log_cost
            description: logistic costs
          - name: ship_cost
            description: shipping costs
              






